#!/usr/bin/lua

local site = require 'gluon.site'
local util = require 'gluon.util'
local uci = require('simple-uci').cursor()

-- make /etc/config/currentsite persistent, if it isn't already
local file = "/etc/sysupgrade.conf"
local configured = false

for line in io.lines(file) do
  if line == "/etc/config/fixedmacs" then
    configured = true
  end
end

if configured == false then
  f = io.open(file,"a")
  f:write("/etc/config/fixmedmacs\n")
  f:close()
end

local wan_mac_enabled = uci:get('fixedmacs', 'wan', 'enabled')
local wan_macaddress = uci:get('fixedmacs', 'wan', 'macaddr')
local wan_o_macaddress = uci:get('fixedmacs', 'wan', 'macaddr_orig')
local wan_orig_macaddress = uci:get('network', 'wan', 'macaddr')

if wan_o_macaddress == nil then
	if wan_orig_macaddress ~= nil then
		uci:set('fixedmacs', 'wan', 'macaddr_orig', wan_orig_macaddress)
		uci:save('fixedmacs')
		uci:commit('fixedmacs')
		wan_o_macaddress = wan_orig_macaddress
	end
end

-- set fixed wan mac address

if wan_mac_enabled ~= nil then
	if tonumber(wan_mac_enabled) ~= 0 then
		if wan_macaddress ~= nil then
			if wan_macaddress ~= '' then
				if wan_macaddress ~= wan_o_macaddress then
					if wan_macaddress ~= wan_orig_macaddress then
						uci:set('network', 'wan', 'macaddr', wan_macaddress)
					end
				end
			end
		end
	else 
		if wan_o_macaddress ~= nil then
			if wan_o_macaddress ~= '' then
				if wan_orig_macaddress ~= wan_o_macaddress then
					uci:set('network', 'wan', 'macaddr', wan_o_macaddress)
					uci:delete('fixedmacs', 'wan', 'macaddr')
					uci:save('fixedmacs')
					uci:commit('fixedmacs')
				end
			end
		end
	end
	uci:save('network')
	uci:commit('network')
end
