#!/usr/bin/lua

local site = require 'gluon.site'
local util = require 'gluon.util'
local uci = require('simple-uci').cursor()

-- make /etc/config/currentsite persistent, if it isn't already
local file = "/etc/sysupgrade.conf"
local configured = false

for line in io.lines(file) do
  if line == "/etc/config/fixedmacs" then
    configured = true
  end
end

if configured == false then
  f = io.open(file,"a")
  f:write("/etc/config/fixmedmacs\n")
  f:close()
end

local wan_mac_enabled = uci:get_bool('fixedmacs', 'wan', 'enabled')
local wan_macaddress = uci:get('fixedmacs', 'wan', 'macaddr')
local wan_base_macaddress = uci:get('fixedmacs', 'wan', 'base_macaddr')
local wan_net_macaddress = uci:get('network', 'wan', 'macaddr')

if wan_base_macaddress == nil and wan_net_macaddress ~= nil then
	uci:set('fixedmacs', 'wan', 'base_macaddr', wan_net_macaddress)
	uci:save('fixedmacs')
	uci:commit('fixedmacs')
	wan_base_macaddress = wan_net_macaddress
end

-- set fixed wan mac address
if wan_mac_enabled then
	if wan_macaddress ~= nil or wan_macaddress ~= '' then
		uci:set('network', 'wan', 'macaddr', wan_macaddress)
	else
		uci:set('network', 'wan', 'enabled', false)
		uci:set('fixedmacs', 'wan', 'base_macaddr', wan_base_macaddress)
	end
else
	if wan_base_macaddress ~= nil and wan_base_macaddress ~= wan_net_macaddress then
		uci:set('network', 'wan', 'macaddr', wan_base_macaddress)
		uci:set('fixedmacs', 'wan', 'base_macaddr', wan_base_macaddress)
	end
end

uci:save('fixedmacs')
uci:save('network')
uci:commit('fixedmacs')
uci:commit('network')
