#!/usr/bin/lua

local util = require 'gluon.util'

local uci = require('luci.model.uci').cursor()
local lutil = require 'luci.util'

-- Delete old broker config section       
uci:delete_all('p910nd', 'p910nd')

local section = uci:add('p910nd', 'p910nd')

uci:section('p910nd', 'p910nd', section,
	  {
		  enabled = '1',
		  bidirectional = '0',
		  port = '0',
		  device = '/dev/usb/lp0',
	  }
)

uci:save('p910nd')
uci:commit('p910nd')

local rule_notset = true
local g
local g1

uci:foreach('firewall', 'rule', function (s)
	if s['.type'] == 'rule' then                         
        g = uci:get('firewall', s['.name'], 'name')          
        if g ~= nil then                                     
        	if g == 'PRINTER' then                            
            	g1 = uci:get('firewall', s['.name'], 'dest_port')
               	if g1 ~= nil then                            
                	if g1 == '9100' then                         
                    	rule_notset = false
                    end
                end
			end
		end
	end
end)


if rule_notset then
	
	local firewall_rule = uci:add('firewall', 'rule')

	uci:section('firewall', 'rule', firewall_rule,
		  {
			  src = 'lan',
			  proto = 'tcp',
			  dest_port = '9100',
			  target = 'ACCEPT',
			  name = 'PRINTER'
		  }
	)

	uci:save('firewall')
	uci:commit('firewall')
end
